language: node_js
node_js: [node]

before_install:
  # Export the C++11 compiler.
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

cache: yarn

env:
  # Do two runs, one for testing and one for linting.
  matrix:
    - TEST_TYPE=lint:eslint
    - TEST_TYPE=lint:prettier

before_script:
  - |
    set -e
    if [[ $TEST_TYPE == 'lint:eslint' ]]; then
      lerna bootstrap
      yarn build
    fi
    set +e

script:
  # Run testing or linting depending on the environment.
  - |
    set -e
    yarn $TEST_TYPE
    set +e
